name: traceability_qr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  # Temporarily commenting out msal_flutter since we are bypassing authentication for now
  # msal_flutter: ^2.0.1
  app_links: ^3.5.0
  url_launcher: ^6.2.5
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
